apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoarder-secrets
  namespace: hoarder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: hoarder-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/hoarder
