apiVersion: v1
kind: LimitRange
metadata:
  name: hoarder-storage-limits
  namespace: hoarder
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "2Gi"
      min:
        storage: "100Mi"
      default:
        storage: "1Gi"
      defaultRequest:
        storage: "500Mi"
