FROM alpine/git:2.45.2 AS source
ARG WEB_POKER_REF=master
WORKDIR /src
RUN git clone --depth 1 --branch "${WEB_POKER_REF}" https://github.com/alexander171294/web-poker.git web-poker
WORKDIR /src/web-poker
COPY containers/web-poker/overrides/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/utils/EmailUtil.java /src/web-poker/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/utils/EmailUtil.java

FROM maven:3.9.9-eclipse-temurin-11 AS build
WORKDIR /work
COPY --from=source /src/web-poker/ ./
COPY containers/web-poker/overrides/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/utils/DockerSecretProcessor.java /work/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/utils/DockerSecretProcessor.java
RUN set -eux; \
    sed -i 's/<version>2.10.0.pr1<\/version>/<version>2.9.5<\/version>/' backend/ApiServer/pom.xml; \
    mvn -f backend/exchange/pom.xml clean install; \
    mvn -f backend/persistence/pom.xml clean install; \
    mvn -f backend/room-int/pom.xml clean install; \
    mvn -f backend/room-poker/room-poker/pom.xml clean install; \
    mvn -f backend/ApiServer/pom.xml clean package -DskipTests

FROM eclipse-temurin:11-jre-jammy
RUN addgroup --system web-poker-api && adduser --system --ingroup web-poker-api --home /home/web-poker-api web-poker-api
USER web-poker-api:web-poker-api
WORKDIR /home/web-poker-api
COPY --from=build /work/backend/ApiServer/target/*.jar /opt/web-poker/api-server.jar
ENV SIGNUP_CHIPS=2500 \
    MAX_BAD_LOGINS=5 \
    SERVER_PORT=8083 \
    LOGGING_LEVEL=WARN \
    FLYWAY=true \
    SMTP_HOST=localhost \
    SMTP_PORT=587 \
    SMTP_USERNAME= \
    SMTP_PASSWORD= \
    SMTP_FROM=poker@levangie.org \
    SMTP_STARTTLS=true \
    SMTP_TRANSPORT=smtp \
    EMAIL_VALIDATION=true \
    DB_URL=jdbc:mysql://web-poker-mysql:3306/poker?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true \
    DB_USERNAME=poker \
    DB_PASSWORD=change-me \
    CORS=https://poker.levangie.dev \
    TZ=America/New_York
ENTRYPOINT ["sh", "-c", "exec java -jar -Duser.timezone=\"$TZ\" -Dar.com.tandilweb.ApiServer.users.initialChips=\"$SIGNUP_CHIPS\" -Dar.com.tandilweb.ApiServer.users.maxBadLogins=\"$MAX_BAD_LOGINS\" -Dspring.flyway.enabled=\"$FLYWAY\" -Dserver.port=\"$SERVER_PORT\" -Dlogging.level.ar.com.tandilweb=\"$LOGGING_LEVEL\" -Dmail.smtpserver=\"$SMTP_HOST\" -Dmail.smtpport=\"$SMTP_PORT\" -Dmail.username=\"$SMTP_USERNAME\" -Dmail.password=\"$SMTP_PASSWORD\" -Dmail.from=\"$SMTP_FROM\" -Dmail.transport=\"$SMTP_TRANSPORT\" -Dmail.starttls=\"$SMTP_STARTTLS\" -Dmail.enabledEmailValidation=\"$EMAIL_VALIDATION\" -Dspring.datasource.url=\"$DB_URL\" -Dspring.datasource.username=\"$DB_USERNAME\" -Dspring.datasource.password=\"$DB_PASSWORD\" -Dspring.cors.allow=\"$CORS\" /opt/web-poker/api-server.jar"]
