FROM alpine/git:2.45.2 AS source
ARG WEB_POKER_REF=master
WORKDIR /src
RUN git clone --depth 1 --branch "${WEB_POKER_REF}" https://github.com/alexander171294/web-poker.git web-poker

FROM maven:3.9.9-eclipse-temurin-11 AS build
WORKDIR /work
COPY --from=source /src/web-poker/ ./
RUN set -eux; \
    sed -i 's/<version>2.10.0.pr1<\/version>/<version>2.9.5<\/version>/' backend/orchestrator/pom.xml; \
    mvn -f backend/exchange/pom.xml clean install; \
    mvn -f backend/persistence/pom.xml clean install; \
    mvn -f backend/room-int/pom.xml clean install; \
    mvn -f backend/room-poker/room-poker/pom.xml clean install; \
    mvn -f backend/orchestrator/pom.xml clean package -DskipTests

FROM eclipse-temurin:11-jre-jammy
RUN addgroup --system web-poker-orchestrator && adduser --system --ingroup web-poker-orchestrator --home /home/web-poker-orchestrator web-poker-orchestrator
USER web-poker-orchestrator:web-poker-orchestrator
WORKDIR /home/web-poker-orchestrator
COPY --from=build /work/backend/orchestrator/target/*.jar /opt/web-poker/orchestrator.jar
ENV SERVER_PORT=8082 \
    LOGGING_LEVEL=WARN \
    CORE_POOL_SIZE=4 \
    MAX_POOL_SIZE=10 \
    ORCHESTRATOR_LISTEN_PORT=8045 \
    DB_URL=jdbc:mysql://web-poker-mysql:3306/poker?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true \
    DB_USERNAME=poker \
    DB_PASSWORD=change-me \
    TZ=America/New_York
ENTRYPOINT ["sh", "-c", "exec java -jar -Duser.timezone=\"$TZ\" -Dserver.port=\"$SERVER_PORT\" -Dlogging.level.ar.com.tandilweb=\"$LOGGING_LEVEL\" -Dact.orchestrator.corePoolSize=\"$CORE_POOL_SIZE\" -Dact.orchestrator.maxPoolSize=\"$MAX_POOL_SIZE\" -Dact.orchestrator.listenPort=\"$ORCHESTRATOR_LISTEN_PORT\" -Dspring.datasource.url=\"$DB_URL\" -Dspring.datasource.username=\"$DB_USERNAME\" -Dspring.datasource.password=\"$DB_PASSWORD\" /opt/web-poker/orchestrator.jar"]
