apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-config
  namespace: plausible
data:
  BASE_URL: "https://plausible.levangie.dev"
  HTTP_PORT: "8000"
  DISABLE_REGISTRATION: "invite_only"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "plausible_db"
  POSTGRES_HOST: "plausible-postgres"
  CLICKHOUSE_DATABASE_URL: "http://plausible-clickhouse:8123/plausible_events_db"
  TZ: "America/New_York"
  clickhouse-ipv4-only.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
    </clickhouse>
  clickhouse-low-resources.xml: |
    <clickhouse>
      <logger>
        <level>warning</level>
      </logger>
      <max_server_memory_usage>2147483648</max_server_memory_usage>
      <max_concurrent_queries>20</max_concurrent_queries>
    </clickhouse>
  z-clickhouse-disable-noisy-logs.xml: |
    <clickhouse>
      <asynchronous_metric_log remove="1"/>
      <metric_log remove="1"/>
      <processors_profile_log remove="1"/>
      <trace_log remove="1"/>
    </clickhouse>
