apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plausible-secrets
  namespace: plausible
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: plausible-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/plausible
        property: DATABASE_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/plausible
        property: POSTGRES_PASSWORD
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: prod/plausible
        property: SECRET_KEY_BASE
    - secretKey: TOTP_VAULT_KEY
      remoteRef:
        key: prod/plausible
        property: TOTP_VAULT_KEY
