apiVersion: v1
kind: LimitRange
metadata:
  name: plausible-storage-limits
  namespace: plausible
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "60Gi"
      min:
        storage: "1Gi"
