apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: factorio
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          metallb.universe.tf/loadBalancerIPs: "172.20.20.205"
commonLabels:
  environment: prod
