apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memory-stack-secrets
  namespace: memory-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: memory-stack-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/memory-stack
