apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Patch ConfigMap APP_URL for stage environment
  - target:
      kind: ConfigMap
      name: bookstack-config
    patch: |
      - op: replace
        path: /data/APP_URL
        value: "https://bookstack.stage.levangie.dev"
  # Patch Ingress host for stage environment
  - target:
      kind: Ingress
      name: bookstack-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "bookstack.stage.levangie.dev"
  - target:
      kind: ExternalSecret
      name: bookstack-secrets
    patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: "stage/bookstack"
commonLabels:
  environment: stage
