apiVersion: v1
kind: LimitRange
metadata:
  name: affine-storage-limits
  namespace: affine
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "50Gi"
      min:
        storage: "1Gi"
