apiVersion: v1
kind: ResourceQuota
metadata:
  name: affine-storage-quota
  namespace: affine
spec:
  hard:
    requests.storage: "70Gi"
    persistentvolumeclaims: "2"
    longhorn.io/requests.storage: "70Gi"
