apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: immich-db-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: immich-db-pv
  - target:
      kind: PersistentVolumeClaim
      name: immich-model-cache-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: immich-model-cache-pv
  - target:
      kind: Ingress
      name: immich-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
  - target:
      kind: Ingress
      name: immich-power-tools-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
