apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/immich-power-tools/immich-power-tools
    newTag: "0.23.0"
patches:
  - target:
      kind: PersistentVolumeClaim
      name: immich-db-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: pvc-13f1eb7c-090a-4a21-935a-e7f9a2ed2718
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
  - target:
      kind: Ingress
      name: immich-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
  - target:
      kind: Ingress
      name: immich-power-tools-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod