apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-secrets
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: headlamp-secrets
    creationPolicy: Owner
  data:
    - secretKey: HEADLAMP_OIDC_CLIENT_ID
      remoteRef:
        key: prod/headlamp
        property: HEADLAMP_OIDC_CLIENT_ID
    - secretKey: HEADLAMP_OIDC_CLIENT_SECRET
      remoteRef:
        key: prod/headlamp
        property: HEADLAMP_OIDC_CLIENT_SECRET
    - secretKey: HEADLAMP_OIDC_ISSUER_URL
      remoteRef:
        key: prod/headlamp
        property: HEADLAMP_OIDC_ISSUER_URL
