apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume.yaml
  - persistent-volume-claim-fileserver.yaml
  - persistent-volume-claim-data.yaml
  - deployment.yaml
  - service.yaml
  - middleware-logout.yaml
  - ingress-logout.yaml
  - ingress.yaml
