apiVersion: v1
kind: Secret
metadata:
  name: librechat-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: librechat-helm-oci
  url: ghcr.io/danny-avila/librechat-chart
  enableOCI: "true"
