apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 3dprintcalc-ingress
  namespace: 3dprintcalc
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  labels:
    app: 3dprintcalc
    app.kubernetes.io/name: 3dprintcalc
spec:
  rules:
    - host: 3dprintcalc.levangie.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: 3dprintcalc
                port:
                  number: 5000
