apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: printcalc-data
  namespace: 3dprintcalc
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi