apiVersion: v1
kind: LimitRange
metadata:
  name: plex-storage-limits
  namespace: plex
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "50Gi"
      min:
        storage: "100Mi"
      default:
        storage: "20Gi"
      defaultRequest:
        storage: "20Gi"
