apiVersion: v1
kind: ResourceQuota
metadata:
  name: plex-storage-quota
  namespace: plex
spec:
  hard:
    requests.storage: "150Gi"
    persistentvolumeclaims: "20"
    longhorn.io/requests.storage: "150Gi"
