apiVersion: v1
kind: Service
metadata:
  name: plex-direct
  namespace: plex
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.20.20.203
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: plex
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
      protocol: TCP
