apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: "2.20.4"
  - name: mariadb
    newTag: "10.11.16"
  - name: redis
    newTag: "7.4.8"
patches:
  - target:
      kind: ConfigMap
      name: paperless-config
    patch: |
      - op: replace
        path: /data/PAPERLESS_URL
        value: "https://paperless.stage.levangie.dev"
  - target:
      kind: Ingress
      name: paperless-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "paperless.stage.levangie.dev"
  - target:
      kind: ExternalSecret
      name: paperless-secrets
    patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: "stage/paperless"
commonLabels:
  environment: stage
