apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-postgres
  namespace: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/hourly: "enabled"
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
