apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    environment: dev
  name: gamble-king-v2-ghcr
spec:
  data:
  - remoteRef:
      key: dev/gamble-king-v2
      property: GHCR_DOCKERCONFIGJSON
    secretKey: dockerconfig
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    creationPolicy: Owner
    name: gamble-king-v2-ghcr
    template:
      data:
        .dockerconfigjson: '{{ .dockerconfig }}'
      type: kubernetes.io/dockerconfigjson
