apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    force-sync: '1787940088'
  labels:
    environment: dev
  name: gamble-king-v2-secrets
spec:
  dataFrom:
  - extract:
      key: dev/gamble-king-v2
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    creationPolicy: Owner
    name: gamble-king-v2-secrets
