apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: car-telemetry-ghcr
  namespace: car-telemetry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: car-telemetry-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: prod/ghcr
        property: GHCR_DOCKER_CONFIG_JSON
