apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-data-pvc
  namespace: wallos
  labels:
    app: wallos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
