apiVersion: v1
kind: ResourceQuota
metadata:
  name: wallos-storage-quota
  namespace: wallos
spec:
  hard:
    requests.storage: "1Gi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "1Gi"
