apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/pocket-id/pocket-id
    newTag: "v1.16.0"
patches:
  - target:
      kind: ConfigMap
      name: pocketid-config
    patch: |
      - op: replace
        path: /data/APP_URL
        value: "https://pocketid.stage.levangie.dev"
  - target:
      kind: Ingress
      name: pocketid-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "pocketid.stage.levangie.dev"
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-stage.levangie.dev"
  - target:
      kind: ExternalSecret
      name: pocketid-secret
    patch: |
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: "stage/pocketid"
commonLabels:
  environment: stage
