apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:jlevangi/home-infra.git
    targetRevision: observability-stage
    path: argocd/manifests/wallos/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: wallos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
