apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: factorio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      securityContext:
        runAsUser: 845
        runAsGroup: 845
        fsGroup: 845
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.76
          ports:
            - containerPort: 34197
              hostPort: 34197
              protocol: UDP
              name: game
            - containerPort: 27015
              hostPort: 27015
              protocol: TCP
              name: rcon
          env:
            - name: LOAD_LATEST_SAVE
              value: "true"
            - name: GENERATE_NEW_SAVE
              value: "true"
            - name: SAVE_NAME
              value: "squidboi"
            - name: DLC_SPACE_AGE
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /factorio
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: factorio-data
