apiVersion: v1
kind: LimitRange
metadata:
  name: factorio-storage-limits
  namespace: factorio
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "5Gi"
      min:
        storage: "100Mi"
