apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-data
  namespace: factorio
  labels:
    recurringjob.group.longhorn.io/hourly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
