apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://minicloudlabs.github.io/helm-charts
    chart: gatus
    targetRevision: 3.4.1
    helm:
      values: |
        image:
          tag: v5.35.0

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          hosts:
            - status.talos-test.levangie.dev

        persistence:
          enabled: true
          storageClassName: longhorn
          size: 1Gi

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        config:
          storage:
            type: sqlite
            path: /data/data.db

          endpoints:
            - name: ArgoCD
              group: Infrastructure
              url: https://argocd.talos-test.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Grafana
              group: Monitoring
              url: https://grafana.talos-test.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Prometheus
              group: Monitoring
              url: http://prometheus-prometheus.monitoring.svc.cluster.local:9090/-/healthy
              interval: 2m
              conditions:
                - "[STATUS] == 200"

            - name: Microbin
              group: Applications
              url: https://bin.talos-test.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"
  destination:
    server: https://kubernetes.default.svc
    namespace: gatus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
