apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netlock-rmm-secrets
  namespace: netlock-rmm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: netlock-rmm-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/netlock-rmm
