apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-mysql.yaml
  - external-secret.yaml
  - deployment-mysql.yaml
  - deployment-server.yaml
  - deployment-console.yaml
  - service-mysql.yaml
  - service-server.yaml
  - service-console.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml
configMapGenerator:
  - name: netlock-server-appsettings
    namespace: netlock-rmm
    files:
      - appsettings.json=appsettings-server.json
  - name: netlock-console-appsettings
    namespace: netlock-rmm
    files:
      - appsettings.json=appsettings-console.json
