apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytdl-ingress
  namespace: ytdl
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: ytdl.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytdl
                port:
                  number: 3033
