apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-config-pvc
  namespace: ytdl
  labels:
    app: ytdl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
