apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: health-postgres-secret
  namespace: health-archive
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: health-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: prod/health-archive
        property: POSTGRES_PASSWORD
