apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-postgres-pvc
  namespace: health-archive
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: health-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-one-replica-flash
  volumeMode: Filesystem
  volumeName: health-postgres-pv
