apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: everlyera-postgres-pvc
  namespace: everlyera
  labels:
    recurring-job-group.longhorn.io/hourly: "enabled"
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: everlyera-postgres
    component: database
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
