apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data-v3-pvc
  namespace: memos
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: memos
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/hourly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
