apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-postgres-pvc
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
