apiVersion: v1
kind: LimitRange
metadata:
  name: calibre-web-storage-limits
  namespace: calibre-web
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "10Gi"
      min:
        storage: "1Gi"
      default:
        storage: "10Gi"
      defaultRequest:
        storage: "10Gi"
