apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
  namespace: calibre-web
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast
