apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - pvc-postgres.yaml
  - pvc-n8n-data.yaml
  - deployment-postgres.yaml
  - deployment-n8n.yaml
  - service-postgres.yaml
  - service-n8n.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml
