apiVersion: v1
kind: LimitRange
metadata:
  name: homepage-storage-limits
  namespace: homepage
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "2Gi"
      min:
        storage: "100Mi"
      default:
        storage: "1Gi"
      defaultRequest:
        storage: "1Gi"
