apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: homepage
  labels:
    app: homepage
    volume-type: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
