---
- name: Restart LVM thin-pool monitoring
  ansible.builtin.service:
    name: lvm2-monitor
    state: restarted

- name: Restart Prometheus node exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true
