apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: luigi311/jellyplex-watched
    newTag: "8.5.3"
  - name: ghcr.io/qdm12/gluetun
    newTag: v3.41.3
  - name: ghcr.io/linuxserver/qbittorrent
    newTag: "5.2.3"
  - name: ghcr.io/flaresolverr/flaresolverr
    newTag: v1.2.4
patches:
  - target:
      kind: PersistentVolumeClaim
      name: tautulli-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: tautulli-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: seerr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: seerr-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: qbittorrent-gluetun-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: qbittorrent-gluetun-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: nzbget-gluetun-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: nzbget-gluetun-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: qbittorrent-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: qbittorrent-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: nzbget-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: nzbget-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: sonarr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: sonarr-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: radarr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: radarr-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: radarr4k-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: radarr4k-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: bazarr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: bazarr-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: prowlarr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: prowlarr-config-pv
  - target:
      kind: PersistentVolumeClaim
      name: wizarr-config-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: wizarr-config-pv
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
    includeSelectors: true
