apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-invite-secrets
  namespace: jellyfin-invite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: jellyfin-invite-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/jellyfin-invite
