apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-invite-ghcr
  namespace: jellyfin-invite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: jellyfin-invite-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"ghcr.io":{"username":"{{ .GHCR_USERNAME }}","password":"{{ .GHCR_TOKEN }}","auth":"{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"}}}
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: prod/jellyfin-invite
        property: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: prod/jellyfin-invite
        property: GHCR_TOKEN
