apiVersion: v1
kind: ResourceQuota
metadata:
  name: snippetbox-storage-quota
  namespace: snippetbox
spec:
  hard:
    requests.storage: "500Mi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "500Mi"
