apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: everlyera-minio-pvc
  namespace: everlyera-media
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: everlyera-minio
    component: object-storage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
