apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: everlyera-filebrowser-pvc
  namespace: everlyera-media
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: everlyera-filebrowser
    component: file-browser
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-redundant
  volumeMode: Filesystem
