apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamble-king
  namespace: gamble-king
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - gambleking-k3s.levangie.dev
  rules:
    - host: gambleking-k3s.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gamble-king
                port:
                  name: http
