apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gamble-king-data
  namespace: gamble-king
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-redundant
  resources:
    requests:
      storage: 1Gi
