apiVersion: v1
kind: Service
metadata:
  name: gamble-king
  namespace: gamble-king
spec:
  selector:
    app.kubernetes.io/name: gamble-king
  ports:
    - name: http
      port: 5000
      targetPort: http
