apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-synapse-config
  namespace: matrix-synapse
data:
  homeserver.yaml: |
    server_name: matrix.levangie.dev
    public_baseurl: https://matrix.levangie.dev/
    serve_server_wellknown: true
    pid_file: /data/homeserver.pid
    signing_key_path: /data/matrix.levangie.dev.signing.key
    media_store_path: /data/media_store
    report_stats: false
    suppress_key_server_warning: true

    listeners:
      - port: 8008
        type: http
        tls: false
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false
      - port: 9090
        type: metrics

    database:
      name: psycopg2
      args:
        user: synapse
        password: "__POSTGRES_PASSWORD__"
        database: synapse
        host: matrix-postgres
        port: 5432
        cp_min: 5
        cp_max: 10

    enable_registration: false
    password_config:
      enabled: false

    oidc_providers:
      - idp_id: keycloak
        idp_name: Keycloak
        issuer: https://auth.levangie.org/realms/master
        client_id: matrix-synapse
        client_secret: "__OIDC_CLIENT_SECRET__"
        scopes: [openid, profile, email]
        backchannel_logout_enabled: true
        user_mapping_provider:
          config:
            localpart_template: "{{ user.preferred_username }}"
            display_name_template: "{{ user.name }}"
            email_template: "{{ user.email }}"

    macaroon_secret_key: "__MACAROON_SECRET_KEY__"
    form_secret: "__FORM_SECRET__"
    trusted_key_servers:
      - server_name: matrix.org

    enable_metrics: true
    max_upload_size: 50M
    url_preview_enabled: false
