apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - pvc-postgres.yaml
  - pvc-synapse.yaml
  - deployment-postgres.yaml
  - deployment-synapse.yaml
  - service-postgres.yaml
  - service-synapse.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml
