apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kioto-postgres-data-pvc
  namespace: kioto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-tank
  volumeName: pvc-5885b9cd-adb5-4086-ad12-7927294a5bda
