apiVersion: v1
kind: ConfigMap
metadata:
  name: trek-config
  namespace: trek
data:
  NODE_ENV: production
  PORT: "3000"
  TZ: America/New_York
  LOG_LEVEL: info
  APP_URL: https://trek.levangie.dev
  ALLOWED_ORIGINS: https://trek.levangie.dev
  FORCE_HTTPS: "true"
  TRUST_PROXY: "1"
  OIDC_ISSUER: https://auth.levangie.org/realms/master
  OIDC_CLIENT_ID: trek
  OIDC_DISPLAY_NAME: Keycloak
  OIDC_ONLY: "true"
  OIDC_SCOPE: openid email profile
