apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - pvc-data.yaml
  - pvc-uploads.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
