apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data
  namespace: trek
  labels:
    app: trek
    volume-type: database
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/hourly: "enabled"
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-redundant
  resources:
    requests:
      storage: 1Gi
