apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/karakeep
