apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.yaml: |
    server:
      port: 8080
      database: /home/filebrowser/data/database.db
      cacheDir: /cache
      externalUrl: https://cloud.levangie.dev
      sources:
        - path: /srv/Public
          name: Public
          config:
            defaultEnabled: true
            defaultUserScope: /
        - path: /srv
          name: Fileserver
          config:
            defaultEnabled: false
            denyByDefault: true
    auth:
      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          issuerUrl: https://auth.levangie.org/realms/master
          scopes: "openid email profile"
          userIdentifier: preferred_username
          adminGroup: filebrowser-admins
          userGroups:
            - filebrowser-users
    userDefaults:
      account:
        loginMethod: oidc
        permissions:
          api: false
          admin: false
          modify: true
          share: true
          realtime: true
          delete: true
          create: true
          download: true
