apiVersion: v1
kind: ResourceQuota
metadata:
  name: komga-storage-quota
  namespace: komga
spec:
  hard:
    requests.storage: "10Gi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "10Gi"
