apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: sissbruecker/linkding
    newTag: "1.45.0"
patches:
  - target:
      kind: ConfigMap
      name: linkding-config
    patch: |
      - op: replace
        path: /data/LD_CSRF_TRUSTED_ORIGINS
        value: "https://linkding.stage.levangie.dev"
  - target:
      kind: Ingress
      name: linkding-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "linkding.stage.levangie.dev"
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-stage.levangie.dev"

labels:
  - pairs:
      environment: stage
    includeSelectors: true
