apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: linkding-config
    patch: |
      - op: replace
        path: /data/LD_CSRF_TRUSTED_ORIGINS
        value: "https://linkding.stage.levangie.dev"
  - target:
      kind: Ingress
      name: linkding-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "linkding.stage.levangie.dev"
  - target:
      kind: Job
      name: linkding-dns-record
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "linkding.stage"
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "k3s-stage.levangie.dev"
commonLabels:
  environment: stage
