apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data-pvc
  namespace: pocketid
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: pocketid
    volume-type: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
