apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worldmonitor
  namespace: worldmonitor
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: worldmonitor.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worldmonitor
                port:
                  number: 8080
