#!/bin/bash

# Helper script to quickly scaffold a new Helm-based application
# Usage: ./scripts/add_helm_app.sh <app_name> <helm_repo_url> <chart_name> <app_url>

set -euo pipefail

APP_NAME="${1:-}"
HELM_REPO_URL="${2:-}"
CHART_NAME="${3:-}"
APP_URL="${4:-}"

if [[ -z "$APP_NAME" || -z "$HELM_REPO_URL" || -z "$CHART_NAME" || -z "$APP_URL" ]]; then
    echo "Usage: $0 <app_name> <helm_repo_url> <chart_name> <app_url>"
    echo "Example: $0 grafana https://grafana.github.io/helm-charts grafana/grafana https://grafana.test"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ANSIBLE_DIR="$PROJECT_ROOT/ansible"

echo "🚀 Creating Helm app: $APP_NAME"

# 1. Create Ansible task file
TASK_FILE="$ANSIBLE_DIR/roles/k3s-apps/tasks/apps/${APP_NAME}.yml"
cat > "$TASK_FILE" << EOF
---
# ${APP_NAME^} Deployment using Reusable Helm Template

- name: Deploy ${APP_NAME^} using reusable Helm template
  include_tasks: ../shared/helm_app_deployment.yml
  vars:
    app_name: "${APP_NAME}"
    helm_config:
      repo_name: "\{{ applications.${APP_NAME}.helm.repo_name }}"
      repo_url: "\{{ applications.${APP_NAME}.helm.repo_url }}"
      chart_name: "\{{ applications.${APP_NAME}.helm.chart_name }}"
      release_name: "\{{ applications.${APP_NAME}.helm.release_name }}"
      namespace: "\{{ applications.${APP_NAME}.helm.namespace }}"
      chart_version: "\{{ applications.${APP_NAME}.helm.chart_version | default(omit) }}"
      values_template: "${APP_NAME}/helm-values.yaml.j2"
    app_config:
      force_redeploy: "\{{ applications.${APP_NAME}.force_redeploy | default(false) }}"
      service_name: "\{{ applications.${APP_NAME}.service_name }}"
      app_url: "\{{ applications.${APP_NAME}.app_url }}"
      service_port: "\{{ applications.${APP_NAME}.service_port }}"
      storage: "\{{ applications.${APP_NAME}.storage }}"
      # pod_selector: "app=\{{ APP_NAME }}"  # Uncomment and customize if needed
EOF

# 2. Create Helm values template directory and file
TEMPLATE_DIR="$ANSIBLE_DIR/roles/k3s-apps/templates/${APP_NAME}"
mkdir -p "$TEMPLATE_DIR"

VALUES_TEMPLATE="$TEMPLATE_DIR/helm-values.yaml.j2"
cat > "$VALUES_TEMPLATE" << EOF
# ${APP_NAME^} Helm Values
# Generated by Ansible for \{{ cluster_environment | default('unknown') }} environment

# Basic configuration - customize based on your chart's values.yaml
# Consult the chart documentation at: $HELM_REPO_URL

# Image configuration (if applicable)
# image:
#   tag: "latest"

# Service configuration
# service:
#   type: ClusterIP
#   port: \{{ ${APP_NAME}_config.service_port | default(80) }}

# Ingress configuration (usually disabled since we handle it separately)
# ingress:
#   enabled: false

# Storage configuration (if applicable)
# persistence:
#   enabled: true
#   size: \{{ ${APP_NAME}_config.storage.config_initial_size | default('1Gi') }}
#   {% if ${APP_NAME}_config.storage.storage_class is defined %}
#   storageClass: \{{ ${APP_NAME}_config.storage.storage_class }}
#   {% endif %}

# Resource configuration
# resources:
#   requests:
#     cpu: \{{ ${APP_NAME}_config.config.resources.requests.cpu | default('100m') }}
#     memory: \{{ ${APP_NAME}_config.config.resources.requests.memory | default('128Mi') }}
#   limits:
#     cpu: \{{ ${APP_NAME}_config.config.resources.limits.cpu | default('500m') }}
#     memory: \{{ ${APP_NAME}_config.config.resources.limits.memory | default('512Mi') }}

# Environment variables (if applicable)
# env:
#   TZ: \{{ ${APP_NAME}_config.config.timezone | default('America/New_York') }}

# Security context (if applicable)
# securityContext:
#   runAsUser: 1000
#   runAsGroup: 1000
#   fsGroup: 1000

# TODO: Customize this template based on your specific Helm chart
# 1. Check the chart's values.yaml for available options
# 2. Configure chart-specific settings
# 3. Remove unused sections
# 4. Test with: helm template $CHART_NAME --values /path/to/this/file
EOF

# 3. Add configuration template to group_vars files
add_to_group_vars() {
    local file="$1"
    
    # Check if app already exists
    if grep -q "^  ${APP_NAME}:" "$file"; then
        echo "⚠️  $APP_NAME already exists in $(basename "$file")"
        return
    fi
    
    # Add the new app configuration
    cat >> "$file" << EOF

  # ${APP_NAME^} Media Server Configuration
  ${APP_NAME}:
    force_redeploy: false
    service_name: "${APP_NAME}"
    app_url: "${APP_URL}"
    service_port: 80  # TODO: Update with correct port
    helm:
      repo_name: "${APP_NAME}"
      repo_url: "${HELM_REPO_URL}"
      chart_name: "${CHART_NAME}"
      release_name: "${APP_NAME}"
      namespace: "${APP_NAME}"
      # chart_version: "1.0.0"  # Uncomment to pin version
    storage:
      config_initial_size: "1Gi"
      max_namespace_storage: "10Gi"
      max_pvc_size: "5Gi"
      default_pvc_size: "1Gi"
      # storage_class: "longhorn"  # Uncomment if using specific storage class
    config:
      timezone: "America/New_York"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
EOF
    
    echo "✅ Added $APP_NAME configuration to $(basename "$file")"
}

# Add to both test and prod group vars
add_to_group_vars "$ANSIBLE_DIR/group_vars/k3s_cluster_test.yml"
add_to_group_vars "$ANSIBLE_DIR/group_vars/k3s_cluster.yml"

# 4. Add to main.yml task list
MAIN_TASKS="$ANSIBLE_DIR/roles/k3s-apps/tasks/main.yml"
if ! grep -q "apps/${APP_NAME}.yml" "$MAIN_TASKS"; then
    # Find the line with "# Add more applications here" or append to end
    if grep -q "# Add more applications here" "$MAIN_TASKS"; then
        sed -i "/# Add more applications here/i - include_tasks: apps/${APP_NAME}.yml" "$MAIN_TASKS"
    else
        echo "- include_tasks: apps/${APP_NAME}.yml" >> "$MAIN_TASKS"
    fi
    echo "✅ Added $APP_NAME to main tasks"
else
    echo "⚠️  $APP_NAME already exists in main tasks"
fi

echo ""
echo "🎉 Successfully scaffolded Helm app: $APP_NAME"
echo ""
echo "📝 Next steps:"
echo "1. Customize the Helm values template: $VALUES_TEMPLATE"
echo "2. Update the group_vars configuration for your specific chart"
echo "3. Test deployment: ansible-playbook -i inventory/hosts.yml site.yml --tags k3s-apps"
echo ""
echo "📚 Useful commands:"
echo "- Check chart values: helm show values $CHART_NAME"
echo "- Test template: helm template test-release $CHART_NAME --values $VALUES_TEMPLATE"
echo "- View generated config: ansible-inventory -i inventory/hosts.yml --list | jq '.all.vars.applications.$APP_NAME'"