apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: raft-secrets
  namespace: raft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: raft-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/raft
