apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
  name: gamble-king-v2-web
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: gamble-king-v2-web
    environment: dev
