apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
  name: gk-postgres-meta
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: gk-postgres-meta
    environment: dev
