apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-poker-storage-quota
  namespace: web-poker
spec:
  hard:
    requests.storage: "25Gi"
    persistentvolumeclaims: "10"
    longhorn.io/requests.storage: "25Gi"
