apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data-pvc
  namespace: ntfy
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: longhorn
