apiVersion: v1
kind: ResourceQuota
metadata:
  name: ntfy-storage-quota
  namespace: ntfy
spec:
  hard:
    requests.storage: "250Mi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "250Mi"
