apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookstack-secrets
  namespace: bookstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: bookstack-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/bookstack
