apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-cron-checker.yaml
  - clusterrole-cron-checker.yaml
  - clusterrolebinding-cron-checker.yaml
  - configmap.yaml
  - external-secret.yaml
  - deployment-oauth2-proxy.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-oauth2-proxy.yaml
  - ingress.yaml
  - ingress-oauth2-proxy.yaml
  - ingress-ping.yaml
  - middleware-oauth2-forwardauth.yaml
  - middleware-oauth2-errors.yaml
  - cronjob-scheduled-job-checks.yaml
  - resource-quota.yaml
  - limit-range.yaml
