apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: semaphore-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/semaphore
