apiVersion: v1
kind: LimitRange
metadata:
  name: semaphore-storage-limits
  namespace: semaphore
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "2Gi"
      min:
        storage: "100Mi"
      default:
        storage: "2Gi"
      defaultRequest:
        storage: "2Gi"
