apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: StorageClass
      name: longhorn-vault-raft
    patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "2"
