apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: gitea-secrets
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: prod/gitea
        property: OIDC_CLIENT_SECRET
