apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export-pvc
  namespace: paperless
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: paperless
    component: export
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/hourly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
