apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-lapi-config
  namespace: crowdsec
data:
  config.yaml: |
    db_config:
      type: sqlite
      db_path: /var/lib/crowdsec/data/crowdsec.db
    api:
      server:
        listen_uri: 0.0.0.0:8080
        online_client: null
        enable_auth: true
        trusted_ips:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
