apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: binwiederhier/ntfy
    newTag: "v2.21.0"
patches:
  - target:
      kind: ConfigMap
      name: ntfy-config
    patch: |
      - op: replace
        path: /data/NTFY_BASE_URL
        value: "https://ntfy.stage.levangie.dev"
  - target:
      kind: Ingress
      name: ntfy-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "ntfy.stage.levangie.dev"
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-stage.levangie.dev"

labels:
  - pairs:
      environment: stage
    includeSelectors: true
