apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: affine-storage-pvc
    patch: |
      - op: replace
        path: /spec/storageClassName
        value: longhorn-one-replica-tank
      - op: add
        path: /spec/volumeName
        value: affine-storage-prod-pv
  - target:
      kind: PersistentVolumeClaim
      name: affine-postgres-pvc
    patch: |
      - op: replace
        path: /spec/storageClassName
        value: longhorn-one-replica-tank
      - op: add
        path: /spec/volumeName
        value: affine-postgres-pv
  - target:
      kind: Ingress
      name: affine-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
    includeSelectors: true
