apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://minicloudlabs.github.io/helm-charts
    chart: gatus
    targetRevision: 3.4.6
    helm:
      values: |
        image:
          tag: v5.35.0

        deployment:
          strategy: Recreate

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            external-dns.alpha.kubernetes.io/target: k3s-prod.levangie.dev
          hosts:
            - status.levangie.dev

        persistence:
          enabled: true
          existingClaim: gatus

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        config:
          metrics: true

          storage:
            type: sqlite
            path: /data/data.db

          endpoints:
            - name: ArgoCD
              group: Infrastructure
              url: https://argocd.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Longhorn
              group: Infrastructure
              url: https://longhorn.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"

            - name: Vault
              group: Infrastructure
              url: https://vault.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Grafana
              group: Monitoring
              url: https://grafana.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Prometheus
              group: Monitoring
              url: http://prometheus-prometheus.monitoring.svc.cluster.local:9090/-/healthy
              interval: 2m
              conditions:
                - "[STATUS] == 200"

            - name: Bookstack
              group: Applications
              url: https://bookstack.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Vaultwarden
              group: Applications
              url: https://vw.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: PocketID
              group: Applications
              url: https://pocketid.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Microbin
              group: Applications
              url: https://bin.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Paperless
              group: Applications
              url: https://paperless.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Factorio
              group: Applications
              url: tcp://factorio.levangie.dev:27015
              interval: 5m
              conditions:
                - "[CONNECTED] == true"

            - name: IT Tools
              group: Applications
              url: https://ittools.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Linkding
              group: Applications
              url: https://linkding.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Ntfy
              group: Applications
              url: https://ntfy.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: PairDrop
              group: Applications
              url: https://pairdrop.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Wallos
              group: Applications
              url: https://wallos.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Immich
              group: Applications
              url: https://photos.levangie.org
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Memos
              group: Applications
              url: https://memos.levangie.org
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Tasks.md
              group: Applications
              url: https://tasks.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Snippet Box
              group: Applications
              url: https://snippets.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Netboot.xyz
              group: Applications
              url: https://netboot.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: 3D Print Calc
              group: Applications
              url: https://3dprintcalc.levangie.org
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Change Detection
              group: Applications
              url: https://changedetection.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Hoarder
              group: Applications
              url: https://hoarder.levangie.org
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: LazyDJ
              group: Applications
              url: https://lazydj.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Note Mark
              group: Applications
              url: https://notemark.levangie.org
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Kioto
              group: Applications
              url: https://koito.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Firefox
              group: Applications
              url: https://firefox.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: SearXNG
              group: Applications
              url: https://search.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Tautulli
              group: Media
              url: https://tautulli.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Seerr
              group: Media
              url: https://request.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Jellyseerr
              group: Media
              url: https://jellyseerr.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Sonarr
              group: Media
              url: https://sonarr.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Radarr
              group: Media
              url: https://radarr.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Radarr 4K
              group: Media
              url: https://radarr4k.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Bazarr
              group: Media
              url: https://bazarr.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Prowlarr
              group: Media
              url: https://prowlarr.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: qBittorrent
              group: Media
              url: https://qbittorrent.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: NZBGet
              group: Media
              url: https://nzbget.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == any(200, 401)"
                - "[RESPONSE_TIME] < 5000"

            - name: Wizarr
              group: Media
              url: https://join.levangie.dev
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"

            - name: Plex
              group: Media
              url: https://plex.levangie.dev/identity
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"
                - "[BODY] == pat(*MediaContainer*)"

            - name: Jellyfin
              group: Media
              url: https://jellyfin.levangie.org/health
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"
                - "[BODY] == Healthy"

            - name: Tracearr
              group: Media
              url: https://tracearr.levangie.org/health
              interval: 5m
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 5000"
                - "[BODY].status == ok"
                - "[BODY].db == true"
                - "[BODY].redis == true"

  destination:
    server: https://kubernetes.default.svc
    namespace: gatus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
