apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:jlevangi/home-infra.git
    targetRevision: main
    path: argocd/manifests/kan/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kan
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/resources/requests/storage
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/dataFrom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
