apiVersion: v1
kind: ConfigMap
metadata:
  name: geopulse-config
  namespace: geopulse
data:
  GEOPULSE_VERSION: "1.33.0"
  GEOPULSE_UI_URL: "https://geopulse.levangie.dev"
  GEOPULSE_CORS_ENABLED: "false"
  GEOPULSE_CORS_ORIGINS: ""
  GEOPULSE_PUBLIC_BASE_URL: "https://geopulse.levangie.dev"
  GEOPULSE_COOKIE_DOMAIN: ""
  GEOPULSE_AUTH_SECURE_COOKIES: "true"
  GEOPULSE_BACKEND_URL: "http://geopulse-backend:8080"
  GEOPULSE_POSTGRES_HOST: "geopulse-postgres"
  GEOPULSE_POSTGRES_PORT: "5432"
  GEOPULSE_POSTGRES_DB: "geopulse"
  GEOPULSE_POSTGRES_USERNAME: "geopulse"
  GEOPULSE_POSTGRES_SHARED_BUFFERS: "256MB"
  GEOPULSE_POSTGRES_WORK_MEM: "8MB"
  GEOPULSE_POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
  GEOPULSE_POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
  GEOPULSE_POSTGRES_MAX_WAL_SIZE: "512MB"
  GEOPULSE_POSTGRES_CHECKPOINT_TARGET: "0.9"
  GEOPULSE_POSTGRES_WAL_BUFFERS: "16MB"
  GEOPULSE_POSTGRES_RANDOM_PAGE_COST: "1.1"
  GEOPULSE_POSTGRES_IO_CONCURRENCY: "100"
  GEOPULSE_POSTGRES_AUTOVACUUM_NAPTIME: "60s"
  GEOPULSE_POSTGRES_VACUUM_SCALE_FACTOR: "0.2"
  GEOPULSE_POSTGRES_LOG_SLOW_QUERIES: "5000"
  GEOPULSE_DATABASE_TRANSACTION_TIMEOUT_MINUTES: "60"
  GEOPULSE_MQTT_ENABLED: "false"
  GEOPULSE_MQTT_BROKER_HOST: "geopulse-mosquitto"
  GEOPULSE_MQTT_BROKER_PORT: "1883"
  GEOPULSE_MQTT_USERNAME: "geopulse_mqtt_admin"
  GEOPULSE_MQTT_TLS_ENABLED: "false"
  GEOPULSE_NOTIFICATIONS_APPRISE_ENABLED: "false"
  GEOPULSE_NOTIFICATIONS_APPRISE_API_URL: ""
  GEOPULSE_NOTIFICATIONS_APPRISE_VERIFY_TLS: "true"
  GEOPULSE_OIDC_ENABLED: "true"
  GEOPULSE_OIDC_CALLBACK_BASE_URL: "https://geopulse.levangie.dev"
  GEOPULSE_AUTH_LOGIN_ENABLED: "true"
  GEOPULSE_AUTH_PASSWORD_LOGIN_ENABLED: "true"
  GEOPULSE_AUTH_OIDC_LOGIN_ENABLED: "true"
  GEOPULSE_AUTH_ADMIN_LOGIN_BYPASS_ENABLED: "true"
  GEOPULSE_AUTH_GUEST_ROOT_REDIRECT_TO_LOGIN_ENABLED: "false"
  GEOPULSE_OIDC_PROVIDER_GOOGLE_ENABLED: "false"
  GEOPULSE_OIDC_PROVIDER_GENERIC_ENABLED: "false"
  GEOPULSE_OIDC_PROVIDER_KEYCLOAK_ENABLED: "true"
  GEOPULSE_OIDC_PROVIDER_KEYCLOAK_NAME: "Keycloak"
  GEOPULSE_OIDC_PROVIDER_GENERIC_NAME: "Custom OIDC"
  CLIENT_MAX_BODY_SIZE: "1000M"
  OSM_RESOLVER: "127.0.0.11 8.8.8.8"
  GEOPULSE_GEOCODING_DELAY_MS: "1000"
  GEOPULSE_GEOCODING_CACHE_MAX_BBOX_AREA_KM2: "5000"
  GEOPULSE_IMPORT_DROP_FOLDER_ENABLED: "false"
  GEOPULSE_IMPORT_DROP_FOLDER_PATH: "/data/geopulse-import"
  GEOPULSE_IMPORT_DROP_FOLDER_POLL_INTERVAL_SECONDS: "10"
  GEOPULSE_IMPORT_DROP_FOLDER_STABLE_AGE_SECONDS: "10"
  GEOPULSE_IMPORT_DROP_FOLDER_GEOPULSE_MAX_SIZE_MB: "200"
  GEOPULSE_SHARE_BASE_URL: ""
  GEOPULSE_GPS_DUPLICATE_DETECTION_LOCATION_TIME_THRESHOLD_MINUTES: "2"
