apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geopulse-ingress
  namespace: geopulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: geopulse.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geopulse-ui
                port:
                  number: 80
