apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geopulse-app-data-pvc
  namespace: geopulse
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: geopulse
    component: app-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
