apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geopulse-postgres-pvc
  namespace: geopulse
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: geopulse-postgres
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
