apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: kube-prometheus-stack-grafana-rdn
    patch: |
      - op: add
        path: /spec/volumeName
        value: pvc-fed126cd-f481-417a-ab45-ded51277ab02
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
