---
# Override sensitive values in vault files or group_vars

# BookStack application settings
bookstack_app_url: "https://bsk3.levangie.org"
bookstack_service_name: "bookstack"
bookstack_service_port: 8080
bookstack_config_storage_size: "5Gi"
bookstack_db_storage_size: "10Gi"
bookstack_db_password: "{{ vault_bookstack_db_password }}"
bookstack_mysql_root_password: "{{ vault_bookstack_mysql_root_password }}"
bookstack_app_key: "{{ vault_bookstack_app_key }}"

# Homepage application settings
homepage_app_url: "https://homepage.levangie.org"
homepage_service_name: "homepage"
homepage_service_port: 3000

# Vaultwarden application settings
vaultwarden_app_url: "https://vw.levangie.dev"
vaultwarden_service_name: "vaultwarden"
vaultwarden_service_port: 80
vaultwarden_data_storage_size: "10Gi"
vaultwarden_admin_token: "{{ vault_vaultwarden_admin_token }}"