apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - persistent-volume.yaml
  - persistent-volume-claim-fileserver.yaml
  - persistent-volume-claim-data.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - deployment-oauth2-proxy.yaml
  - service-oauth2-proxy.yaml
  - ingress-oauth2-proxy.yaml
  - middleware-oauth2-forwardauth.yaml
  - middleware-oauth2-errors.yaml
