apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boxbox-data
  namespace: boxbox
  labels:
    app.kubernetes.io/name: boxbox
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-redundant
