apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: llama-swap-config
    namespace: llama-cpp
    files:
      - config.yaml=config.yaml
    options:
      labels:
        app: llama-cpp
