apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf-secrets
  namespace: stirling-pdf
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: stirling-pdf-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: prod/stirling-pdf
