apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - pvc-configs.yaml
  - pvc-tessdata.yaml
  - pvc-storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml
