apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-configs-pvc
  namespace: stirling-pdf
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
