apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget-secrets
  namespace: actual-budget
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: actual-budget-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/actual-budget
