apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-config
  namespace: linkding
data:
  LD_CONTEXT_PATH: ""
  LD_DISABLE_BACKGROUND_TASKS: "False"
  LD_DISABLE_URL_VALIDATION: "False"
  LD_ENABLE_AUTH_PROXY: "False"
  LD_CSRF_TRUSTED_ORIGINS: "https://linkding.levangie.dev"
  LD_ENABLE_OIDC: "True"
  OIDC_RP_CLIENT_ID: "linkding"
  OIDC_RP_SIGN_ALGO: "RS256"
  OIDC_OP_AUTHORIZATION_ENDPOINT: "https://auth.levangie.org/realms/master/protocol/openid-connect/auth"
  OIDC_OP_TOKEN_ENDPOINT: "https://auth.levangie.org/realms/master/protocol/openid-connect/token"
  OIDC_OP_USER_ENDPOINT: "https://auth.levangie.org/realms/master/protocol/openid-connect/userinfo"
  OIDC_OP_JWKS_ENDPOINT: "https://auth.levangie.org/realms/master/protocol/openid-connect/certs"
  OIDC_USE_PKCE: "True"
