apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/linkding
