apiVersion: v1
kind: ResourceQuota
metadata:
  name: linkding-storage-quota
  namespace: linkding
spec:
  hard:
    requests.storage: "1Gi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "1Gi"
