apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-db.yaml
  - configmap.yaml
  - external-secret.yaml
  - deployment-postgres.yaml
  - service-postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml

configMapGenerator:
  - name: keycloak-theme-levangie
    namespace: keycloak
    files:
      - theme.properties=theme/login/theme.properties
      - levangie.css=theme/login/resources/css/levangie.css
      - levangie-dev.png=theme/login/resources/img/levangie-dev.png
      - messages_en.properties=theme/login/messages/messages_en.properties
