apiVersion: v1
kind: ResourceQuota
metadata:
  name: keycloak-storage-quota
  namespace: keycloak
spec:
  hard:
    requests.storage: "20Gi"
    persistentvolumeclaims: "10"
    longhorn.io/requests.storage: "20Gi"
