apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-secrets
  namespace: frigate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: frigate-secrets
    creationPolicy: Owner
  data:
    - secretKey: FRIGATE_MQTT_USER
      remoteRef:
        key: prod/frigate
        property: FRIGATE_MQTT_USER
    - secretKey: FRIGATE_MQTT_PASSWORD
      remoteRef:
        key: prod/frigate
        property: FRIGATE_MQTT_PASSWORD
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: prod/frigate
        property: OIDC_CLIENT_SECRET
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: prod/frigate
        property: OAUTH2_PROXY_COOKIE_SECRET
    - secretKey: FRIGATE_PROXY_SECRET
      remoteRef:
        key: prod/frigate
        property: FRIGATE_PROXY_SECRET
