apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-flash
  resources:
    requests:
      storage: 10Gi
