apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    app: frigate
  ports:
    - name: proxy-http
      port: 4180
      targetPort: proxy-http
      protocol: TCP
