apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: "3.0.0"
  - name: mariadb
    newTag: "12.3.2"
  - name: redis
    newTag: "8.8.0"
patches:
  - target:
      kind: PersistentVolumeClaim
      name: paperless-data-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
      - op: replace
        path: /spec/volumeName
        value: paperless-data-pv
  - target:
      kind: PersistentVolumeClaim
      name: paperless-media-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
      - op: replace
        path: /spec/volumeName
        value: paperless-media-pv
  - target:
      kind: PersistentVolumeClaim
      name: paperless-export-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
      - op: replace
        path: /spec/volumeName
        value: paperless-export-pv
  - target:
      kind: PersistentVolumeClaim
      name: paperless-db-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
      - op: replace
        path: /spec/volumeName
        value: paperless-db-pv
  - target:
      kind: PersistentVolumeClaim
      name: paperless-redis-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
      - op: replace
        path: /spec/volumeName
        value: paperless-redis-pv
  - target:
      kind: ResourceQuota
      name: paperless-storage-quota
    patch: |
      - op: replace
        path: /spec/hard/requests.storage
        value: "40Gi"
      - op: replace
        path: /spec/hard/longhorn.io~1requests.storage
        value: "40Gi"
  - target:
      kind: Deployment
      name: paperless
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          httpGet:
            path: /
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 90
  - target:
      kind: Ingress
      name: paperless-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
    includeSelectors: true
