apiVersion: v1
kind: Service
metadata:
  name: paperless-gpt
  namespace: paperless
spec:
  selector:
    app: paperless-gpt
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
