apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: changedetection-ingress
  namespace: changedetection
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: changedetection.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: changedetection
                port:
                  number: 5000
