apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data-pvc
  namespace: changedetection
  labels:
    app: changedetection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
