apiVersion: v1
kind: ConfigMap
metadata:
  name: netbootxyz-nginx-conf
  namespace: netbootxyz
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location /isos/ {
            alias /isos/;
            autoindex on;
        }

        location /custom/ {
            alias /config/custom-assets/;
        }

        location / {
            return 404;
        }

        location = /404.html {
            internal;
        }
    }
