apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - job-migrate-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - resource-quota.yaml
  - limit-range.yaml
