apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-data-pvc
  namespace: netbootxyz
  labels:
    app: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
