apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-data-pvc
  namespace: netbootxyz
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
