apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: plexinc/pms-docker
    newTag: "1.42.1.10054-f333bdaa8"
patches:
  - target:
      kind: Ingress
      name: plex-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: "plex.stage.levangie.dev"
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-stage.levangie.dev"
commonLabels:
  environment: stage
