apiVersion: v1
kind: LimitRange
metadata:
  name: vaultwarden-storage-limits
  namespace: vaultwarden
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "10Gi"
      min:
        storage: "100Mi"
      default:
        storage: "5Gi"
      defaultRequest:
        storage: "5Gi"
