apiVersion: v1
kind: LimitRange
metadata:
  name: open-notebook-limits
  namespace: open-notebook
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 4Gi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
