apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: open-notebook-oauth2-errors
  namespace: open-notebook
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: 4180
    query: /oauth2/sign_in?rd={url}
