apiVersion: v1
kind: ResourceQuota
metadata:
  name: open-notebook-quota
  namespace: open-notebook
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
    requests.storage: 30Gi
