apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: tess1o/geopulse-backend
    newTag: "1.36.1-native"
  - name: tess1o/geopulse-ui
    newTag: "1.36.1"
  - name: postgis/postgis
    newTag: "17-3.5"
patches:
  - target:
      kind: PersistentVolumeClaim
      name: geopulse-app-data-pvc
    patch: |
      - op: add
        path: /spec/volumeName
        value: pvc-680e9dc2-c02f-4460-aebc-282dd3f986fe
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
  - target:
      kind: PersistentVolumeClaim
      name: geopulse-postgres-pvc
    patch: |
      - op: add
        path: /spec/volumeName
        value: pvc-981e40ab-c8b2-4638-9898-2f6ff258ae36
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
  - target:
      kind: Ingress
      name: geopulse-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
    includeSelectors: true
