apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasksmd-data-pvc
  namespace: tasksmd
  labels:
    app: tasksmd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
