apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasksmd-data-pvc
  namespace: tasksmd
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: tasksmd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
