apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notemark-data-pvc
  namespace: notemark
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: notemark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn-general
