apiVersion: v1
kind: ResourceQuota
metadata:
  name: notemark-storage-quota
  namespace: notemark
spec:
  hard:
    requests.storage: "500Mi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "500Mi"
