apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: pingvin-share-x
  labels:
    app.kubernetes.io/name: clamav
    app.kubernetes.io/part-of: pingvin-share-x
spec:
  selector:
    app.kubernetes.io/name: clamav
  ports:
    - name: clamd
      port: 3310
      targetPort: clamd
      protocol: TCP
