apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pingvin-share-x-config
  namespace: pingvin-share-x
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: pingvin-share-x-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          general:
            appName: "Levangie File Transfer"
            appUrl: "https://files.levangie.dev"
            secureCookies: "true"
            showHomePage: "true"
            sessionDuration: "3 months"
          share:
            allowRegistration: "false"
            allowUnauthenticatedShares: "false"
            maxExpiration: "30 days"
            shareIdLength: "12"
            maxSize: "53687091200"
            zipCompressionLevel: "0"
            chunkSize: "10000000"
            autoOpenShareModal: "true"
            allowAdminAccessAllShares: "true"
            fileRetentionPeriod: "7 days"
          oauth:
            allowRegistration: "true"
            ignoreTotp: "true"
            disablePassword: "false"
            oidc-enabled: "true"
            oidc-discoveryUri: "https://auth.levangie.org/realms/master/.well-known/openid-configuration"
            oidc-signOut: "true"
            oidc-scope: "openid email profile"
            oidc-usernameClaim: "preferred_username"
            oidc-rolePath: "groups"
            oidc-roleGeneralAccess: "pingvin-users"
            oidc-roleAdminAccess: "pingvin-admins"
            oidc-clientId: "{{ .OIDC_CLIENT_ID }}"
            oidc-clientSecret: "{{ .OIDC_CLIENT_SECRET }}"
          s3:
            enabled: "false"
          initUser:
            enabled: true
            username: "bootstrap-admin"
            email: "pierce@levangie.org"
            password: "{{ .BOOTSTRAP_ADMIN_PASSWORD }}"
            isAdmin: true
            ldapDN: ""
  dataFrom:
    - extract:
        key: prod/pingvin-share-x
