apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingvin-share-x
  namespace: pingvin-share-x
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: files.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingvin-share-x
                port:
                  number: 3000
    - host: share.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingvin-share-x
                port:
                  number: 3000
