apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingvin-share-x-files
  namespace: pingvin-share-x
  labels:
    app.kubernetes.io/name: pingvin-share-x
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: pingvin-share-x-nfs
  volumeName: pingvin-share-x-files
