apiVersion: v1
kind: Service
metadata:
  name: pingvin-share-x
  namespace: pingvin-share-x
  labels:
    app.kubernetes.io/name: pingvin-share-x
spec:
  selector:
    app.kubernetes.io/name: pingvin-share-x
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
