apiVersion: v1
kind: ConfigMap
metadata:
  name: outline-config
  namespace: outline
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  NODE_ENV: "production"
  URL: "https://outline.levangie.dev"
  PORT: "3000"
  PGSSLMODE: "disable"
  FILE_STORAGE: "local"
  FILE_STORAGE_LOCAL_ROOT_DIR: "/var/lib/outline/data"
  FILE_STORAGE_UPLOAD_MAX_SIZE: "262144000"
  FORCE_HTTPS: "false"
  OIDC_AUTH_URI: "https://auth.levangie.org/realms/master/protocol/openid-connect/auth"
  OIDC_TOKEN_URI: "https://auth.levangie.org/realms/master/protocol/openid-connect/token"
  OIDC_USERINFO_URI: "https://auth.levangie.org/realms/master/protocol/openid-connect/userinfo"
  OIDC_LOGOUT_URI: "https://auth.levangie.org/realms/master/protocol/openid-connect/logout"
  OIDC_USERNAME_CLAIM: "preferred_username"
  OIDC_DISPLAY_NAME: "Keycloak"
  OIDC_SCOPES: "openid offline_access profile email"
  RATE_LIMITER_ENABLED: "true"
  WEB_CONCURRENCY: "1"
