apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/outline
