apiVersion: v1
kind: Service
metadata:
  name: outline-postgres
  namespace: outline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: outline-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
