apiVersion: v1
kind: ResourceQuota
metadata:
  name: termix-storage-quota
  namespace: termix
spec:
  hard:
    requests.storage: "2Gi"
    persistentvolumeclaims: "1"
    longhorn.io/requests.storage: "2Gi"
