apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-keycloak-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: argocd-keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: prod/argocd
        property: OIDC_CLIENT_SECRET
