---
kubeconfig_path: ""
platform_primary_node_ip: ""
platform_master_nodes: []
platform_cluster_nodes: []
platform_cluster_node_count: 0

platform_install_longhorn: true
platform_install_metallb: true
platform_install_traefik: true
platform_install_argocd: true
platform_configure_vault: true

longhorn_default_data_path: "/var/lib/longhorn"

longhorn_namespace_pod_security_enforce: ""
longhorn_namespace_pod_security_audit: ""
longhorn_namespace_pod_security_warn: ""

metallb_namespace_pod_security_enforce: ""
metallb_namespace_pod_security_audit: ""
metallb_namespace_pod_security_warn: ""
