apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: immich-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/immich
