apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-power-tools-data-pvc
  namespace: immich
  labels:
    app: immich-power-tools
    volume-type: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
