{
 "title": "Home Assistant",
 "tags": [
  "home-assistant",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Scrape Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"home-assistant\"}",
     "legendFormat": "Home Assistant"
    }
   ]
  },
  {
   "title": "Home Occupancy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{job=\"home-assistant\",entity=\"binary_sensor.home_is_occupied\"}",
     "legendFormat": "Home"
    }
   ]
  },
  {
   "title": "Average House Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{job=\"home-assistant\",entity=\"sensor.average_house_temp\"} * 9 / 5 + 32",
     "legendFormat": "Average house"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{job=\"home-assistant\",entity=\"sensor.average_house_humidity\"}",
     "legendFormat": "Average house"
    }
   ]
  },
  {
   "title": "Occupancy",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{job=\"home-assistant\",friendly_name=~\".*Occupancy.*|Home is Occupied\",friendly_name!~\".*Motion.*|.*Zone.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(homeassistant_sensor_battery_percent{job=\"home-assistant\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperature By Room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{job=\"home-assistant\",entity=~\"sensor[.](average_house_temp|office_temperature_sensor_temperature|bedroom_temperature_sensor_temperature|living_room_temp_sensor_temperature|kitchen_temperature_sensor_temperature)\"} * 9 / 5 + 32",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "homeassistant_climate_current_temperature_celsius{job=\"home-assistant\"} * 9 / 5 + 32",
     "legendFormat": "Thermostat current"
    },
    {
     "expr": "homeassistant_climate_target_temperature_celsius{job=\"home-assistant\"} * 9 / 5 + 32",
     "legendFormat": "Thermostat target"
    }
   ]
  },
  {
   "title": "Humidity By Room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{job=\"home-assistant\",entity=~\"sensor[.](average_house_humidity|office_temperature_sensor_humidity|bedroom_temperature_sensor_humidity|living_room_temp_sensor_humidity|kitchen_temperature_sensor_humidity)\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Illuminance Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_illuminance_lx{job=\"home-assistant\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power Sensors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{job=\"home-assistant\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}