apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-assistant
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 60s
      authorization:
        credentials:
          name: home-assistant-prometheus-token
          key: token
