apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: rustdesk/rustdesk-server
    newTag: "1.1.16"
labels:
  - pairs:
      environment: prod
    includeSelectors: true
