apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lazydj-secrets
  namespace: lazydj
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: lazydj-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/lazydj
