apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: neosmemo/memos
    newTag: "0.27.1"
patches:
  - target:
      kind: PersistentVolumeClaim
      name: memos-data-v3-pvc
    patch: |
      - op: add
        path: /spec/volumeName
        value: memos-data-v3
  - target:
      kind: Ingress
      name: memos-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
