apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/firecrawl/firecrawl
    newTag: latest
  - name: ghcr.io/firecrawl/playwright-service
    newTag: latest
  - name: redis
    newTag: alpine
  - name: postgres
    newTag: "18"
patches:
  - target:
      kind: Ingress
      name: firecrawl-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "k3s-prod.levangie.dev"
labels:
  - pairs:
      environment: prod
    includeSelectors: true