apiVersion: v1
kind: LimitRange
metadata:
  name: oauth2-proxy-limits
  namespace: oauth2-proxy
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: 25m
        memory: 64Mi
