apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      environment: prod
patches:
  - target:
      kind: PersistentVolumeClaim
      name: everlyera-gallery-model-cache-pvc
    patch: |
      - op: add
        path: /spec/volumeName
        value: pvc-a4cbad7a-1ada-43c4-8d35-74ea35aba461
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
  - target:
      kind: PersistentVolumeClaim
      name: everlyera-gallery-db-pvc
    patch: |
      - op: add
        path: /spec/volumeName
        value: pvc-3609b2f2-eee3-4e1d-a2ed-5bc3652f88f0
      - op: replace
        path: /spec/storageClassName
        value: longhorn-flash
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
  - target:
      kind: Ingress
      name: everlyera-gallery-ingress
    patch: |
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "172.20.20.200"
