apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent-browser-cdp-ingress
  namespace: agent-browser
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: browser-cdp.levangie.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agent-browser
                port:
                  number: 9222
