apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-registration
  namespace: gitea-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: gitea-runner-registration
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: prod/gitea-runner
      property: REGISTRATION_TOKEN
