apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- resourcequota.yaml
- limitrange.yaml
- networkpolicy.yaml
- externalsecret.yaml
- configmap.yaml
- statefulset.yaml
