apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitea-runner-pilot
  namespace: gitea-runner
spec:
  hard:
    pods: '3'
    requests.cpu: '2'
    requests.memory: 3Gi
    limits.cpu: '3'
    limits.memory: 5Gi
    requests.ephemeral-storage: 8Gi
    limits.ephemeral-storage: 12Gi
