apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - pvc-postgres.yaml
  - deployment-postgres.yaml
  - service-postgres.yaml
  - job-migrate.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
