apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kan-postgres
  namespace: kan
  labels:
    recurring-job-group.longhorn.io/hourly: "enabled"
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-tank
  volumeMode: Filesystem
