apiVersion: v1
kind: LimitRange
metadata:
  name: rustdesk-limit-range
  namespace: rustdesk
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 250m
        memory: 256Mi
