apiVersion: v1
kind: ResourceQuota
metadata:
  name: jellyfin-storage-quota
  namespace: jellyfin
spec:
  hard:
    requests.storage: "200Gi"
    persistentvolumeclaims: "20"
    longhorn.io/requests.storage: "200Gi"
