apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracearr-data-pvc
  namespace: jellyfin
  labels:
    recurring-job-group.longhorn.io/daily: "enabled"
    recurring-job-group.longhorn.io/weekly: "enabled"
    app: tracearr
    volume-type: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
